server:
  port: 9999

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/mmall?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: '0725'
    driver-class-name: com.mysql.cj.jdbc.Driver

  thymeleaf:
    cache: false

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-enums-package: com.aynu.enums #扫描枚举包
  mapperLocations: classpath*:com/aynu/mapper/xml/*Mapper.xml
  # 配置Mybatis数据返回类型别名（默认别名为类名）
  type-aliases-package: com.aynu.entity